// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: grpcproxy/proto/v1/grpcproxy.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Union:
	//
	//	*Packet_Payload
	//	*Packet_ConnectRequest
	//	*Packet_ConnectResponse
	Union isPacket_Union `protobuf_oneof:"union"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproxy_proto_v1_grpcproxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproxy_proto_v1_grpcproxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_grpcproxy_proto_v1_grpcproxy_proto_rawDescGZIP(), []int{0}
}

func (m *Packet) GetUnion() isPacket_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (x *Packet) GetPayload() []byte {
	if x, ok := x.GetUnion().(*Packet_Payload); ok {
		return x.Payload
	}
	return nil
}

func (x *Packet) GetConnectRequest() *ConnectRequest {
	if x, ok := x.GetUnion().(*Packet_ConnectRequest); ok {
		return x.ConnectRequest
	}
	return nil
}

func (x *Packet) GetConnectResponse() *ConnectResponse {
	if x, ok := x.GetUnion().(*Packet_ConnectResponse); ok {
		return x.ConnectResponse
	}
	return nil
}

type isPacket_Union interface {
	isPacket_Union()
}

type Packet_Payload struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3,oneof"`
}

type Packet_ConnectRequest struct {
	ConnectRequest *ConnectRequest `protobuf:"bytes,2,opt,name=connect_request,json=connectRequest,proto3,oneof"`
}

type Packet_ConnectResponse struct {
	ConnectResponse *ConnectResponse `protobuf:"bytes,3,opt,name=connect_response,json=connectResponse,proto3,oneof"`
}

func (*Packet_Payload) isPacket_Union() {}

func (*Packet_ConnectRequest) isPacket_Union() {}

func (*Packet_ConnectResponse) isPacket_Union() {}

type ConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostPort string `protobuf:"bytes,1,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproxy_proto_v1_grpcproxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproxy_proto_v1_grpcproxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_grpcproxy_proto_v1_grpcproxy_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectRequest) GetHostPort() string {
	if x != nil {
		return x.HostPort
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproxy_proto_v1_grpcproxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproxy_proto_v1_grpcproxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_grpcproxy_proto_v1_grpcproxy_proto_rawDescGZIP(), []int{2}
}

var File_grpcproxy_proto_v1_grpcproxy_proto protoreflect.FileDescriptor

var file_grpcproxy_proto_v1_grpcproxy_proto_rawDesc = []byte{
	0x0a, 0x22, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x1a, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x3a, 0x0a, 0x0f, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x22,
	0x2d, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x11,
	0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0x2a, 0x0a, 0x09, 0x48, 0x54, 0x54, 0x50, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x1d,
	0x0a, 0x03, 0x52, 0x75, 0x6e, 0x12, 0x07, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x07,
	0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x32, 0x5a,
	0x30, 0x67, 0x69, 0x74, 0x2e, 0x63, 0x61, 0x74, 0x62, 0x6f, 0x2e, 0x6e, 0x65, 0x74, 0x2f, 0x6d,
	0x75, 0x72, 0x61, 0x76, 0x6a, 0x6f, 0x76, 0x2f, 0x67, 0x6f, 0x32, 0x30, 0x32, 0x33, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcproxy_proto_v1_grpcproxy_proto_rawDescOnce sync.Once
	file_grpcproxy_proto_v1_grpcproxy_proto_rawDescData = file_grpcproxy_proto_v1_grpcproxy_proto_rawDesc
)

func file_grpcproxy_proto_v1_grpcproxy_proto_rawDescGZIP() []byte {
	file_grpcproxy_proto_v1_grpcproxy_proto_rawDescOnce.Do(func() {
		file_grpcproxy_proto_v1_grpcproxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcproxy_proto_v1_grpcproxy_proto_rawDescData)
	})
	return file_grpcproxy_proto_v1_grpcproxy_proto_rawDescData
}

var file_grpcproxy_proto_v1_grpcproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpcproxy_proto_v1_grpcproxy_proto_goTypes = []interface{}{
	(*Packet)(nil),          // 0: Packet
	(*ConnectRequest)(nil),  // 1: ConnectRequest
	(*ConnectResponse)(nil), // 2: ConnectResponse
}
var file_grpcproxy_proto_v1_grpcproxy_proto_depIdxs = []int32{
	1, // 0: Packet.connect_request:type_name -> ConnectRequest
	2, // 1: Packet.connect_response:type_name -> ConnectResponse
	0, // 2: HTTPProxy.Run:input_type -> Packet
	0, // 3: HTTPProxy.Run:output_type -> Packet
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpcproxy_proto_v1_grpcproxy_proto_init() }
func file_grpcproxy_proto_v1_grpcproxy_proto_init() {
	if File_grpcproxy_proto_v1_grpcproxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcproxy_proto_v1_grpcproxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproxy_proto_v1_grpcproxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproxy_proto_v1_grpcproxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_grpcproxy_proto_v1_grpcproxy_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Packet_Payload)(nil),
		(*Packet_ConnectRequest)(nil),
		(*Packet_ConnectResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcproxy_proto_v1_grpcproxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcproxy_proto_v1_grpcproxy_proto_goTypes,
		DependencyIndexes: file_grpcproxy_proto_v1_grpcproxy_proto_depIdxs,
		MessageInfos:      file_grpcproxy_proto_v1_grpcproxy_proto_msgTypes,
	}.Build()
	File_grpcproxy_proto_v1_grpcproxy_proto = out.File
	file_grpcproxy_proto_v1_grpcproxy_proto_rawDesc = nil
	file_grpcproxy_proto_v1_grpcproxy_proto_goTypes = nil
	file_grpcproxy_proto_v1_grpcproxy_proto_depIdxs = nil
}
